/**
 * News-friendly one-line explanations. Checked before API lookup.
 * Keys are lowercased lookup strings.
 */
export const JARGON_GLOSSARY = {
  inflation: 'Prices rising over time — your money buys a bit less than before.',
  recession: 'A stretch when the economy shrinks and jobs and spending usually slow.',
  gdp: 'Roughly: everything the country produces and sells in a year, added up.',
  'repo rate': 'The rate at which the central bank lends to banks — it nudges loan and deposit rates.',
  'basis points': 'Tiny units for rates: 100 basis points = 1 percentage point.',
  valuations: 'How pricey stocks or assets look compared to earnings or fundamentals.',
  commodity: 'Raw goods traded globally — oil, wheat, metals — often priced in world markets.',
  'purchasing power': 'What your money can actually buy; it falls when prices rise faster than income.',
  'food inflation': 'Rising prices for food — it hits household budgets first.',
  deflation: 'The opposite of inflation: falling prices, which can also hurt growth.',
  yields: 'What you earn on bonds or savings, shown as a percentage.',
  equities: 'Another word for stocks — shares in companies.',
  'deepfake': 'Fake audio or video made with AI so it looks or sounds real.',
  'kessler syndrome': 'A runaway chain reaction of space junk collisions that could clutter orbit.',
  'range anxiety': 'Worry that an electric vehicle will run out of charge before you find a charger.',
  algorithmic: 'Done by automated rules or AI rather than only by humans.',
  geopolitical: 'How countries\' politics and power affect trade, security, and markets.',
  bwssb: 'Bangalore\'s public water supply board — plans pipes, treatment, and distribution.',
  'demand management': 'Spreading or shifting electricity use to avoid blackouts at peak times.',
  'foreign exchange': 'Trading one currency for another — matters for imports and debt.',
  'food and agriculture organisation': 'UN agency that tracks global food prices and hunger data.',
  fao: 'UN Food and Agriculture Organisation — publishes global food price trends.',
  'black sea': 'A major grain export region; disruptions there move wheat markets worldwide.',
  'edible oil': 'Cooking oils like palm and sunflower — many countries import a large share.',
  'global south': 'A loose label for lower- and middle-income countries, often former colonies.',
  'ai act': 'EU law sorting AI systems by risk and setting rules for high-risk uses.',
  'facial recognition': 'Tech that matches faces in images or video — sensitive for privacy.',
  'impact assessment': 'A structured check of harms and fairness before rolling out a system.',
  'supply chain': 'The steps from raw materials to the product you buy.',
  lithium: 'A light metal used in most EV batteries — much of it is imported into India.',
  gigafactory: 'A very large battery or EV component plant.',
  'space debris': 'Dead satellites and fragments zipping around Earth — collision risk.',
  'low earth orbit': 'The band a few hundred km up where many satellites and junk circle Earth.',
  debunking: 'Showing a claim is false with evidence — often slower than the lie spreads.',
  'interest rate': 'The extra you pay on loans or earn on savings, as a percentage per year.',
  'policy rate': 'The central bank\'s main benchmark rate that guides other borrowing costs.',
  'core inflation': 'Price rises excluding volatile food and fuel — shows underlying pressure.',
  headways: 'Time between buses or trains arriving — predictable headways mean shorter waits.',
  'heat exhaustion': 'Heavy sweating, weakness, and nausea from heat — can worsen without care.',
  acclimated: 'Your body getting used to heat or altitude over time.',
}
